### ISSUE TITLE
error when trying to run sample app

### ISSUE THREAD

**Issue by placebocurejava** [privettoli/openam-integration#1]
Hi, 

i get this error while trying to open your app ?
any idea please?
![sans titre](https://cloud.githubusercontent.com/assets/18368701/17976991/67f0d50e-6adf-11e6-98c3-13392b1292e6.png)

**Comment by privettoli** [comment]
You need to install SASS.
http://sass-lang.com

**Comment by placebocurejava** [comment]
could you told me what is sass please?
is it a kind of keylogger ?  :)

**Comment by privettoli** [comment]
@placebocurejava, RTFM

**Comment by placebocurejava** [comment]
Ohhhh i am sorry for bothering.
Ciao.

Le 25 août 2016 17:43, "Anatoly Papenko" notifications@github.com a
écrit :
